version: '3.8'

services:
  db:
    image: postgres
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
