MIGRATIONS_PATH=./src/migrations

migration-generate:
	npm run migration:generate ${MIGRATIONS_PATH}/${name}

migration-run:
	npm run migration:run

migration-show:
	npm run migration:show

migration-revert:
	npm run migration:revert
